# Generated by Django 2.2.1 on 2019-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ManyToManyField(to='menu.Menu'),
        ),
    ]
